// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using pruebaNexos.Models;

namespace pruebaNexos.Migrations
{
    [DbContext(typeof(DBContext))]
    [Migration("20200823225612_Pruba")]
    partial class Pruba
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("pruebaNexos.Entities.Citas", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Doctores")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pacientes")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Citas");
                });

            modelBuilder.Entity("pruebaNexos.Entities.Doctores", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("doc_cedula")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("doc_especialidad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("doc_hospital")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("doc_nombre_completo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("doc_num_credencial")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Doctores");
                });

            modelBuilder.Entity("pruebaNexos.Entities.Pacientes", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("pac_cedula")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pac_cod_postal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pac_nombre_completo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pac_num_seguro_social")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pac_telefono")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Pacientes");
                });
#pragma warning restore 612, 618
        }
    }
}
